version: "3.8"

services:
  app:
    image: front-portfolio
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    command: npm start
